import SwiftUI

// MARK: - Cathier Design Tokens
// Color tokens (cathierAccent, cathierAccentLight, cathierSage, cathierSageLight,
// cathierBackground, cathierSurface) are auto-generated by Xcode from Assets.xcassets
// into GeneratedAssetSymbols.swift — no manual Color extension needed here.

// MARK: - Typography

extension Font {
    /// Instrument Serif for reflection moments: check-in prompts, AI feedback, pattern insights.
    ///
    /// To activate: add InstrumentSerif-Regular.ttf and InstrumentSerif-Italic.ttf to the
    /// Xcode project target, then add both file names under UIAppFonts in Info.plist.
    /// Until then, iOS falls back to the system serif (Georgia).
    static func cathierSerif(_ textStyle: Font.TextStyle = .body, italic: Bool = false) -> Font {
        let name = italic ? "InstrumentSerif-Italic" : "InstrumentSerif-Regular"
        return Font.custom(name, size: textStylePointSize(textStyle), relativeTo: textStyle)
    }

    private static func textStylePointSize(_ style: Font.TextStyle) -> CGFloat {
        switch style {
        case .largeTitle:  return 34
        case .title:       return 28
        case .title2:      return 22
        case .title3:      return 20
        case .headline:    return 17
        case .body:        return 17
        case .callout:     return 16
        case .subheadline: return 15
        case .footnote:    return 13
        case .caption:     return 12
        case .caption2:    return 11
        @unknown default:  return 17
        }
    }
}
